---
# handlers file for gitlab_app
# Handler
- name: Reconfigure GitLab
  command: /opt/gitlab/bin/gitlab-ctl reconfigure
  become: true
  environment:
    PATH: "/opt/gitlab/bin:/opt/gitlab/embedded/bin:{{ ansible_env.PATH }}"
